FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install && npm install -g serve
COPY . .
EXPOSE 5173
ENTRYPOINT ["sh", "run.sh"]
CMD ["serve","-s", "dist","-l","5173"]
# CMD ["npm","run", "dev"]