-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER');

-- CreateEnum
CREATE TYPE "Mut" AS ENUM ('NAN', 'M15', 'M45', 'H8', 'FOREVER');

-- CreateEnum
CREATE TYPE "Type" AS ENUM ('PRIVATE', 'PROTECTED', 'PUBLIC');

-- CreateTable
CREATE TABLE "USER" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "gameWon" INTEGER NOT NULL,
    "gameLost" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "achievements" TEXT[],

    CONSTRAINT "USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Match_History" (
    "id" TEXT NOT NULL,
    "user1Id" TEXT NOT NULL,
    "user2Id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user1P" INTEGER NOT NULL,
    "user2P" INTEGER NOT NULL,

    CONSTRAINT "Match_History_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FRIENDSHIP" (
    "id" TEXT NOT NULL,
    "userID" TEXT NOT NULL,
    "friendID" TEXT NOT NULL,
    "blocked" BOOLEAN NOT NULL,
    "isRequested" BOOLEAN NOT NULL,
    "isFriend" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FRIENDSHIP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PARTICIPANTS" (
    "channelID" TEXT NOT NULL,
    "userID" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'USER',
    "blocked" BOOLEAN NOT NULL DEFAULT false,
    "mut" "Mut" NOT NULL DEFAULT 'NAN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PARTICIPANTS_pkey" PRIMARY KEY ("channelID","userID")
);

-- CreateTable
CREATE TABLE "CHANNEL" (
    "id" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "type" "Type" NOT NULL DEFAULT 'PRIVATE',
    "name" TEXT NOT NULL,
    "hash" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CHANNEL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MESSAGES" (
    "id" TEXT NOT NULL,
    "channelID" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "timeSend" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MESSAGES_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "MESSAGES_channelID_key" ON "MESSAGES"("channelID");

-- AddForeignKey
ALTER TABLE "Match_History" ADD CONSTRAINT "Match_History_user1Id_fkey" FOREIGN KEY ("user1Id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Match_History" ADD CONSTRAINT "Match_History_user2Id_fkey" FOREIGN KEY ("user2Id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FRIENDSHIP" ADD CONSTRAINT "FRIENDSHIP_userID_fkey" FOREIGN KEY ("userID") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FRIENDSHIP" ADD CONSTRAINT "FRIENDSHIP_friendID_fkey" FOREIGN KEY ("friendID") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_channelID_fkey" FOREIGN KEY ("channelID") REFERENCES "CHANNEL"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_userID_fkey" FOREIGN KEY ("userID") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHANNEL" ADD CONSTRAINT "CHANNEL_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGES" ADD CONSTRAINT "MESSAGES_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGES" ADD CONSTRAINT "MESSAGES_channelID_fkey" FOREIGN KEY ("channelID") REFERENCES "CHANNEL"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
