version: '3.8'

services:
  postgresql-db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./server/.env
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - ft_transcendence
  nestjs:
    container_name: nestjs
    build: 
      context: ./server
    ports:
      - 3000:3000
      - 5555:5555
    restart: always
    depends_on:
      - postgresql-db
    env_file:
      - ./server/.env
    networks:
      - ft_transcendence
  react:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - clientV:/app
    depends_on:
      - postgresql-db
    networks:
      - ft_transcendence

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server/Data
  clientV:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client/

networks:
  ft_transcendence:
    driver: bridge
