version: '3.8'
services:
  postgresql-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ft_transcendence
networks:
  ft_transcendence:

  # docker-compose --env-file .env  up -d postgresql-db
  # npm rebuild argon2 --build-from-source