FROM node

WORKDIR /app

COPY package*.json ./

COPY in.sh ./

RUN npm install --force

COPY . .

EXPOSE 3000

ENTRYPOINT ["sh", "in.sh"]

CMD ["npm", "run", "start"]
# CMD ["npm", "run", "start:dev"]