FROM node:20.3.0-alpine

WORKDIR /app

COPY  package*.json ./

RUN rm -rf node_modules

RUN npm cache clean --force

RUN npm install

ENV PYTHON=/path/to/python

COPY script.sh .

RUN chmod +x script.sh

CMD [ "./script.sh" ]

