FROM node:20.3.0-alpine

WORKDIR /app

# Install build dependencies
RUN apk update && apk add --no-cache python3 make g++

# Install global dependencies
RUN  npm install --global node-gyp \
    && npm install --global prisma

COPY  package*.json ./

RUN rm -rf node_modules

RUN npm install

ENV PYTHON=/path/to/python

COPY script.sh .

RUN npm rebuild argon2 --build-from-source

RUN chmod +x script.sh

# CMD [ "./script.sh" ]
CMD [ "npm", "run", "start:dev" ]
